//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Resources/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""BattleMap"",
            ""id"": ""b6ae9aa3-ce34-424b-a68c-2539a6e68797"",
            ""actions"": [
                {
                    ""name"": ""Select1"",
                    ""type"": ""Button"",
                    ""id"": ""23dd2e27-7fdb-4606-b488-15c2e7961f2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select2"",
                    ""type"": ""Button"",
                    ""id"": ""3d205058-db73-4131-b745-f0cc154892b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select3"",
                    ""type"": ""Button"",
                    ""id"": ""1290ed40-9ce8-47dd-9964-75d9daeba737"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select4"",
                    ""type"": ""Button"",
                    ""id"": ""f8134fe1-0adb-4665-9a94-ea01a8d4e33e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select5"",
                    ""type"": ""Button"",
                    ""id"": ""95da2f6e-22f3-42b4-a217-40bc4b67936e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select6"",
                    ""type"": ""Button"",
                    ""id"": ""c0470d92-261c-4955-bd33-a7387e961047"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select7"",
                    ""type"": ""Button"",
                    ""id"": ""ab29e3b4-5fa6-42bc-8b10-80524e865e50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select8"",
                    ""type"": ""Button"",
                    ""id"": ""9efd60d7-86ad-4659-8665-d3e7841b5cfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select9"",
                    ""type"": ""Button"",
                    ""id"": ""8181719a-b8b3-4e45-bc73-9c1ee7e34c57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select10"",
                    ""type"": ""Button"",
                    ""id"": ""cbc9f44a-18db-4375-b971-4a78f4a146f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cf7967f4-5b37-402d-80ae-6ea7600afd62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ab7846f9-648a-4905-bbff-499c127097a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a06d0885-413d-4bd7-b391-15c51120d980"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""37176e5b-039b-4ac9-8e08-d8bc60b6f4d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClickDrag"",
                    ""type"": ""PassThrough"",
                    ""id"": ""70a2dce9-d8b0-4d68-b313-31efd93e11c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.05,pressPoint=0.1)"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c018f6e7-a14b-493c-9911-1657f1c3282e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b096b7e6-4bad-4c33-9aff-2e7366508f25"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d68a5e8-7caf-420c-bb0e-e645221805d7"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f79a65a9-77e8-4fb3-8739-d4db34d2ba35"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10412ce1-0c13-4d26-b397-466fc7a43558"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68f1c4a5-873f-4af9-9f31-0845b85c9be0"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfa4f815-6913-4268-b72c-8d0c53ff2403"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b7f645f-43e3-42de-9c83-949144689929"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d00149da-c903-4250-94fa-308a9ad598c3"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d49479ca-f4a6-4cab-84e2-24d3167d7014"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""891e5e04-e99a-427c-956c-f32577cb5db7"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d33f2b78-00bf-45de-a049-f109897604c6"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11b87b91-80cc-4bc5-a3d3-02581110ca7d"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bebff9f-32b5-4ca1-808b-23ccbc573edd"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a25ba08d-dba1-4e0f-b4be-73d59337417a"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""feb8a0f4-dd60-455c-80a4-5a150e724f7c"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a109e9f-4eff-4cbc-ba1a-d1f0bf9a0a52"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""721486d9-73e4-4a91-bb9c-880c59af1d29"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a04d3e1d-4db2-4156-9292-624abb795bbc"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa44351c-1867-4333-8265-7d789c204ce9"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e742ab7-6730-4698-9d0b-493a19fb23fc"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0e54816-e66f-4f46-8bd8-b2b9a3319eee"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aae8378-9352-4813-8fef-43cf77f68635"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9516e066-b8d7-4df2-a77f-b871265f3a89"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a6fdcbc-f8f7-4123-87e8-dfbed551ab42"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aaadcd2a-6338-4d0c-a472-79695c8fa685"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da3d9c4b-c60a-4d9c-98ad-bd41118fb026"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7aa9f24-4a08-4406-8fc9-359ef24cac58"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea5e94c4-5f68-4ab8-916d-4ed1b7653f20"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43bd8f40-c4da-4210-835b-bb64755b9dbc"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClickDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
        // BattleMap
        m_BattleMap = asset.FindActionMap("BattleMap", throwIfNotFound: true);
        m_BattleMap_Select1 = m_BattleMap.FindAction("Select1", throwIfNotFound: true);
        m_BattleMap_Select2 = m_BattleMap.FindAction("Select2", throwIfNotFound: true);
        m_BattleMap_Select3 = m_BattleMap.FindAction("Select3", throwIfNotFound: true);
        m_BattleMap_Select4 = m_BattleMap.FindAction("Select4", throwIfNotFound: true);
        m_BattleMap_Select5 = m_BattleMap.FindAction("Select5", throwIfNotFound: true);
        m_BattleMap_Select6 = m_BattleMap.FindAction("Select6", throwIfNotFound: true);
        m_BattleMap_Select7 = m_BattleMap.FindAction("Select7", throwIfNotFound: true);
        m_BattleMap_Select8 = m_BattleMap.FindAction("Select8", throwIfNotFound: true);
        m_BattleMap_Select9 = m_BattleMap.FindAction("Select9", throwIfNotFound: true);
        m_BattleMap_Select10 = m_BattleMap.FindAction("Select10", throwIfNotFound: true);
        m_BattleMap_LeftClick = m_BattleMap.FindAction("LeftClick", throwIfNotFound: true);
        m_BattleMap_Point = m_BattleMap.FindAction("Point", throwIfNotFound: true);
        m_BattleMap_ScrollWheel = m_BattleMap.FindAction("ScrollWheel", throwIfNotFound: true);
        m_BattleMap_RightClick = m_BattleMap.FindAction("RightClick", throwIfNotFound: true);
        m_BattleMap_RightClickDrag = m_BattleMap.FindAction("RightClickDrag", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BattleMap
    private readonly InputActionMap m_BattleMap;
    private IBattleMapActions m_BattleMapActionsCallbackInterface;
    private readonly InputAction m_BattleMap_Select1;
    private readonly InputAction m_BattleMap_Select2;
    private readonly InputAction m_BattleMap_Select3;
    private readonly InputAction m_BattleMap_Select4;
    private readonly InputAction m_BattleMap_Select5;
    private readonly InputAction m_BattleMap_Select6;
    private readonly InputAction m_BattleMap_Select7;
    private readonly InputAction m_BattleMap_Select8;
    private readonly InputAction m_BattleMap_Select9;
    private readonly InputAction m_BattleMap_Select10;
    private readonly InputAction m_BattleMap_LeftClick;
    private readonly InputAction m_BattleMap_Point;
    private readonly InputAction m_BattleMap_ScrollWheel;
    private readonly InputAction m_BattleMap_RightClick;
    private readonly InputAction m_BattleMap_RightClickDrag;
    public struct BattleMapActions
    {
        private @GameInputs m_Wrapper;
        public BattleMapActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select1 => m_Wrapper.m_BattleMap_Select1;
        public InputAction @Select2 => m_Wrapper.m_BattleMap_Select2;
        public InputAction @Select3 => m_Wrapper.m_BattleMap_Select3;
        public InputAction @Select4 => m_Wrapper.m_BattleMap_Select4;
        public InputAction @Select5 => m_Wrapper.m_BattleMap_Select5;
        public InputAction @Select6 => m_Wrapper.m_BattleMap_Select6;
        public InputAction @Select7 => m_Wrapper.m_BattleMap_Select7;
        public InputAction @Select8 => m_Wrapper.m_BattleMap_Select8;
        public InputAction @Select9 => m_Wrapper.m_BattleMap_Select9;
        public InputAction @Select10 => m_Wrapper.m_BattleMap_Select10;
        public InputAction @LeftClick => m_Wrapper.m_BattleMap_LeftClick;
        public InputAction @Point => m_Wrapper.m_BattleMap_Point;
        public InputAction @ScrollWheel => m_Wrapper.m_BattleMap_ScrollWheel;
        public InputAction @RightClick => m_Wrapper.m_BattleMap_RightClick;
        public InputAction @RightClickDrag => m_Wrapper.m_BattleMap_RightClickDrag;
        public InputActionMap Get() { return m_Wrapper.m_BattleMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattleMapActions set) { return set.Get(); }
        public void SetCallbacks(IBattleMapActions instance)
        {
            if (m_Wrapper.m_BattleMapActionsCallbackInterface != null)
            {
                @Select1.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect1;
                @Select1.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect1;
                @Select1.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect1;
                @Select2.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect2;
                @Select2.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect2;
                @Select2.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect2;
                @Select3.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect3;
                @Select3.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect3;
                @Select3.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect3;
                @Select4.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect4;
                @Select4.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect4;
                @Select4.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect4;
                @Select5.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect5;
                @Select5.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect5;
                @Select5.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect5;
                @Select6.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect6;
                @Select6.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect6;
                @Select6.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect6;
                @Select7.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect7;
                @Select7.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect7;
                @Select7.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect7;
                @Select8.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect8;
                @Select8.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect8;
                @Select8.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect8;
                @Select9.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect9;
                @Select9.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect9;
                @Select9.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect9;
                @Select10.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect10;
                @Select10.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect10;
                @Select10.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnSelect10;
                @LeftClick.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnLeftClick;
                @Point.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnPoint;
                @ScrollWheel.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnScrollWheel;
                @RightClick.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClick;
                @RightClickDrag.started -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClickDrag;
                @RightClickDrag.performed -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClickDrag;
                @RightClickDrag.canceled -= m_Wrapper.m_BattleMapActionsCallbackInterface.OnRightClickDrag;
            }
            m_Wrapper.m_BattleMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Select1.started += instance.OnSelect1;
                @Select1.performed += instance.OnSelect1;
                @Select1.canceled += instance.OnSelect1;
                @Select2.started += instance.OnSelect2;
                @Select2.performed += instance.OnSelect2;
                @Select2.canceled += instance.OnSelect2;
                @Select3.started += instance.OnSelect3;
                @Select3.performed += instance.OnSelect3;
                @Select3.canceled += instance.OnSelect3;
                @Select4.started += instance.OnSelect4;
                @Select4.performed += instance.OnSelect4;
                @Select4.canceled += instance.OnSelect4;
                @Select5.started += instance.OnSelect5;
                @Select5.performed += instance.OnSelect5;
                @Select5.canceled += instance.OnSelect5;
                @Select6.started += instance.OnSelect6;
                @Select6.performed += instance.OnSelect6;
                @Select6.canceled += instance.OnSelect6;
                @Select7.started += instance.OnSelect7;
                @Select7.performed += instance.OnSelect7;
                @Select7.canceled += instance.OnSelect7;
                @Select8.started += instance.OnSelect8;
                @Select8.performed += instance.OnSelect8;
                @Select8.canceled += instance.OnSelect8;
                @Select9.started += instance.OnSelect9;
                @Select9.performed += instance.OnSelect9;
                @Select9.canceled += instance.OnSelect9;
                @Select10.started += instance.OnSelect10;
                @Select10.performed += instance.OnSelect10;
                @Select10.canceled += instance.OnSelect10;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @RightClickDrag.started += instance.OnRightClickDrag;
                @RightClickDrag.performed += instance.OnRightClickDrag;
                @RightClickDrag.canceled += instance.OnRightClickDrag;
            }
        }
    }
    public BattleMapActions @BattleMap => new BattleMapActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IBattleMapActions
    {
        void OnSelect1(InputAction.CallbackContext context);
        void OnSelect2(InputAction.CallbackContext context);
        void OnSelect3(InputAction.CallbackContext context);
        void OnSelect4(InputAction.CallbackContext context);
        void OnSelect5(InputAction.CallbackContext context);
        void OnSelect6(InputAction.CallbackContext context);
        void OnSelect7(InputAction.CallbackContext context);
        void OnSelect8(InputAction.CallbackContext context);
        void OnSelect9(InputAction.CallbackContext context);
        void OnSelect10(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnRightClickDrag(InputAction.CallbackContext context);
    }
}
